version: "3"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mailer-app
    ports:
      - 5000:5000

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass mailer-app
    volumes:
      - cache:/data
    networks:
      - mailer-app

  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mailer-app
      - MYSQL_PASSWORD=mailer-app
      - MYSQL_DATABASE=mailer-app
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - mailer-app

volumes:
  mysql_data:
    driver: local
  cache:
    driver: local

networks:
  mailer-app:
    driver: bridge

