"""Initial migration

Revision ID: 532a5f5e3366
Revises: 
Create Date: 2023-07-22 18:06:13.921107

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532a5f5e3366'
down_revision = None
branch_labels = None
depends_on = None

def utc_now():
    return datetime.utcnow()
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=False),
    sa.Column('email_content', sa.Text(), nullable=False),
    sa.Column('email_send_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('email_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, server_default=sa.text('NOW()')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
